### ISSUE TITLE
Can't install driver on Windows 10 x64

### ISSUE THREAD

**Issue by Cobertos** [elepro/Anthony#2]
The device comes up in Device Manager and I try to update the driver software yet I get an error while doing so.

My OS is Windows 10 x64, I'm using the latest release version of Anthony in the .zip (0102)

See image below:

![Image with error](http://i.imgur.com/dHrTmeA.png)

Here's the above image transcribed:
> Windows encountered a problem installing the driver software for your device.
> 
> Windows found driver software for your device but encountered an error while attempting to install it.
> 
> MEMORY CARD ADAPTER
> 
> A problem was encountered while attempting to add the driver to the store
> 
> If you know the manufacturer of your device, you can visit its website and check the support section for driver software.

**Comment by elepro** [comment]
Did you restart Windows 10 with driver signature enforcement disabled?

Please try this:
https://www.howtogeek.com/167723/how-to-disable-driver-signature-verification-on-64-bit-windows-8.1-so-that-you-can-install-unsigned-drivers/

**Comment by Cobertos** [comment]
That was it! Thank you very much :D
