### ISSUE TITLE
Support for PS2 cards

### ISSUE THREAD

**Issue by Cobertos** [elepro/Anthony#3]
Is there any plans to support PS2 memory cards? I'm just curious what technical limitations there are that currently prohibit their use in the Anthony software and whether there might be some potential to contribute there.

**Comment by elepro** [comment]
I don't have technical information to do this.
and I worry about legal issue in my country.
I recognize that PS2 memory card have something encryption.

**Comment by DeadlySystem** [comment]
@Coburn37 ps3mca tool is a software that can do this. You can download it here (this comes bundled with an installation script for FMCB):
http://psx-scene.com/forums/attachments/f153/27875d1308560149-ps3-memory-card-adaptor-cechzm1-allows-free-mc-boot-install-ps3mca-tool-fmcb-1.8c.zip
http://psx-scene.com/forums/attachments/f153/28232d1309157066-ps3-memory-card-adaptor-cechzm1-allows-free-mc-boot-install-ps3mca-windrv.zip

The source code can be obtained here, in case you are interested in extending Anthony.

http://www.mediafire.com/download/czzi9i143c17rra/jimmikaelkael-ps3mca-tool-12a198f.zip

**Comment by elepro** [comment]
I've tried that library.
It seems that I have succeeded to read whole pages of PS2 Memory Card.
But that library doesn't have "mcio_mcWritePage" function.
please help.

**Comment by DeadlySystem** [comment]
I'm not sure how it works, but it definitely can write as the FMCB installer works. The source might be outdated. The original author is this guy: https://github.com/jimmikaelkael He might be able to tell you more. I haven't looked deep into the source code myself yet, but quickly looking at the implementation of mcio_mcReadPage you see that it's just forwarding the call to Card_ReadPage, and that one does a bit of ECC magic and relies on Card_ReadPageData to actually read from the MC. There is an analogous Card_WritePageData which should take care of the writing ;)

**Comment by elepro** [comment]
I've succeeded to create .PS2 image file from Memory Card.
But I don't have a way to write back to Memory Card yet.

**Comment by elepro** [comment]
I tried to write "mcio_mcWriteBlock" function on my own.
It seems that I have succeeded to write back to Memory Card.
